# make sure all hooks are invoked
import dispersionreticle.hooks.aih_global_binding_hooks
import dispersionreticle.hooks.aih_hooks
import dispersionreticle.hooks.avatar_hooks
import dispersionreticle.hooks.crosshair_panel_container_hooks
import dispersionreticle.hooks.crosshair_proxy_hooks
import dispersionreticle.hooks.data_provider_hooks
import dispersionreticle.hooks.gun_marker_ctrl_hooks
import dispersionreticle.hooks.gun_marker_factory_hooks
import dispersionreticle.hooks.gun_markers_invalidate_plugin_hooks
import dispersionreticle.hooks.gun_marker_components_hooks
import dispersionreticle.hooks.vehicle_gun_rotator_hooks
